### ISSUE TITLE
Suggestion: select section and no point

### ISSUE THREAD

**Issue by McGiverGim** [danimart1991/pvpc-hourly-pricing-card#10]
In the graph, to see the price of some hour, we need to select the point where the hour starts.

This had sense in the old style where it was a continuous line and only the starting point was at the right hour/price. 

Now the graph is divided into sections, one per hour, and the complete section marks the correct hour/price. Can the complete section be used to select the hour? Will be a lot easier, specially for mobile, to select one hour to see the price and I think it represents better the graph.

If you make this change, maybe is better too to move a little to the right the max and min markers in the graph, to be in the center of the section and not in the starting point. Again I think this will represent a lot better the contents of the graph.

Thanks!

**Comment by danimart1991** [comment]
Available in 1.1.x
