### ISSUE TITLE
Wrong detection of minimum cost hour

### ISSUE THREAD

**Issue by McGiverGim** [danimart1991/pvpc-hourly-pricing-card#11]
Hi! This is what I've seen today:

- The card is showing the minimum cost at 5:00 to 6:00 hour.

![Screenshot_20200428-214256](https://user-images.githubusercontent.com/2673520/80530547-74c09080-8999-11ea-891b-44b26c45dace.png)

- The price is correct, but the reality is that it is from 11:00 to 12:00

![Screenshot_20200428-214310](https://user-images.githubusercontent.com/2673520/80530754-c406c100-8999-11ea-94b6-69ea89fa0537.png)

It seems that it repeats the data of today in the tomorrow data.

**Comment by danimart1991** [comment]
Fixed in next release (1.0.0).
