### ISSUE TITLE
Configuracion visual grafico en modo oscuro

### ISSUE THREAD

**Issue by clavi69** [danimart1991/pvpc-hourly-pricing-card#14]
Sobre el tema por defecto de Home Assistant la visualizacion del grafico es correcta con la ultima update de las barras, pero sobre un tema en modo oscuro no se ven las barras.
¿Quizas alguna configuracion extra es necesaria?
![Grafico](https://user-images.githubusercontent.com/59062002/80860438-e2a1dc00-8c67-11ea-9f73-70cf420418a0.jpg)

**Comment by danimart1991** [comment]
El color de los divisores en tu caso es el mismo que el del fondo, por eso tampoco se ven los dividores. Aún así he cambiado el color del selector para que sea parecido al de los iconos. En la siguiente versión deberíar verlo correctamente.

![image](https://user-images.githubusercontent.com/5982912/80907882-d62a8b80-8d1a-11ea-80e6-32cdcc079825.png)
