### ISSUE TITLE
Cannot select the Card

### ISSUE THREAD

**Issue by malarconfresno** [danimart1991/pvpc-hourly-pricing-card#17]
Hello, 
Following the steps on the web, I have come to configure the card in Home Assistant with version 0.05, but when I update to 1.00 or higher, I get an error when selecting the card, which shows in red: NotSupportedError : Failed to execute 'define' on 'CustomElementRegistry': the name "pvpc-hourly-pricing-card-editor" has already been used with this registry
Could it be something from the selection check?
Any ideas, since I find the card very interesting. Thank you

**Comment by danimart1991** [comment]
Could you bring more info, please? Where is this error showed? Are you working in visual mode?

Thanks for your issue.

**Comment by malarconfresno** [comment]
I have 2 instances of HomeAssistant. A clean one just installed today in HassOS.
I am using Lovelace visual mode. I have included the two .js files in /www/pvpc-hourly-pricing-card/pvpc-hourly-pricing-card.js
I have gone to settings / lovelace panel / resource. I have added the path of the 2 js.
Once I have refreshed the browser cache, I go to the Lovelace section. I add the card. In the preview of the card the error message appears in red: NotSupportedError: Error executing 'define' in 'CustomElementRegistry': the name "pvpc-hourly-priceing-card-card-editor" has already been used with this registry. I attach a screenshot
[capture](https://drive.google.com/file/d/1X2GvJfFIIki7tEZ-to8YK7ne_24ffvUx/view?usp=sharing)

**Comment by danimart1991** [comment]
The `...editor.js` doesn't need to be included in resources. Try to remove it.

**Comment by malarconfresno** [comment]
It has worked!!! 
After refreshing the browser and restarting HomeAssistant. The other time, I would say delete the file ...- editor.js but I shouldn't have restarted.
Thank you very much and magnificent work

**Comment by danimart1991** [comment]
Bug closed.
