### ISSUE TITLE
Error color icono tararjeta

### ISSUE THREAD

**Issue by clavi69** [danimart1991/pvpc-hourly-pricing-card#19]
Con la ultima actualización de home assistant a la 0.112.0 el icono de la tarjeta que cambia de verde a rojo para indicar si se esta en periodo barato o caro de la luz ha dejando de funcionar y ahora esta siempre en negro
![Captura de pantalla 2020-07-02 a las 23 05 40](https://user-images.githubusercontent.com/59062002/86409212-ae26bc80-bcb8-11ea-8ffc-ccc8d14a2624.png)

**Comment by McGiverGim** [comment]
Iba a comentar lo mismo...
![Screenshot_20200702-230745](https://user-images.githubusercontent.com/2673520/86409340-f940cf80-bcb8-11ea-8f53-0650078f1afc.png)

**Comment by McGiverGim** [comment]
Si ayuda, examinando el código, parece que no se está rellenando el "fill" del svg que dibuja el círculo:

![image](https://user-images.githubusercontent.com/2673520/86463662-37c4a180-bd2e-11ea-8ad6-e0e29ceced15.png)

Según el código entiendo que debe rellenarse según la tarifa:
https://github.com/danimart1991/pvpc-hourly-pricing-card/blob/191e5b8b1e993cc429cc2b5bd27a9d096a9faef9/dist/pvpc-hourly-pricing-card.js#L213-L218

No sé que habrá cambiado en esta versión para que esto deje de funcionar.

**Comment by McGiverGim** [comment]
Depurando un poco, el `style`, que contiene el `getComputedStyle(document.body);`, no contiene los estilos definidos en la tabla `tariffPeriodIconColors`. He visto que son colores típicos de Material Design. ¿Tal vez hayan cambiado por parte de Google o por parte de Home Assistant?

**Comment by McGiverGim** [comment]
Creo que esto está relacionado: https://github.com/home-assistant/frontend/issues/6254

**Comment by McGiverGim** [comment]
Según ese link, hay que cambiar en:
```javascript
const tariffPeriodIconColors = {
  error: '--error-color',
  normal: '--google-yellow-500',
  peak: '--google-red-500',
  valley: '--google-green-500',
  'super-valley': '--google-blue-500'
};
```
Lo siguiente:
- `--google-red-500` por `--error-color` que ya se está usando para error, lo cual no sé si será buena idea...
- `--google-green-500` por `--success-color`
- `--google-blue-500` y `--google-yellow-500` no tienen equivalencia directa

Por lo tanto lo mismo te toca buscar otros colores en general más adecuados para todo.

**Comment by danimart1991** [comment]
Muchas gracias por avisar del error y por la investigación, me ha facilitado mucho arreglarlo.

**Comment by McGiverGim** [comment]
No sé si estará relacionado, pero los textos de los switch en el editor tampoco se ven, ni con la versión que ya tiene este fix:
![Screenshot_20200704-000009](https://user-images.githubusercontent.com/2673520/86499097-7fc4e200-bd89-11ea-84fd-c7751789d2f4.png)

**Comment by danimart1991** [comment]
He creado una nueva Issue para tenerlo en cuenta. Muchas gracias.
