### ISSUE TITLE
Uncaught TypeError: Cannot read property '_model' of undefined

### ISSUE THREAD

**Issue by javiw200s** [danimart1991/pvpc-hourly-pricing-card#21]
Hello, 

I get this error "hacsfiles/pvpc-hourly-pricing-card/pvpc-hourly-pricing-card.js:365:81 Uncaught TypeError: Cannot read property '_model' of undefined".
The card worked correctly one day, then appears the error.
How to solve the error?
Thanks a lot for your help and great work.

**Comment by javiw200s** [comment]
More Details:
The first day when it worked good the graphic showed 2 lines, today prices & tomorrow prices.
When fails only show today prices line and minimum and maximum prices appear with NaN text.
And normally the graphic disappears.
See bellow screenshots.

![No Graphic line](https://user-images.githubusercontent.com/57770725/88832391-0a560100-d1d1-11ea-958f-52d771bdae13.jpg)
![When fails](https://user-images.githubusercontent.com/57770725/88832394-0aee9780-d1d1-11ea-880f-7c0409d707d2.jpg)

Thanks.

**Comment by javiw200s** [comment]
More Details:
Just, the sensor has the data of tomorrow prices the behaviour come back to good condition.
Seems that the card behaviour is not good if the sensor don't have all the data needed by the card.

I don't know if the error "Uncaught TypeError: Cannot read property '_model' of undefined" is related with this behaviour.

Thanks.

**Comment by danimart1991** [comment]
Hi @javiw200s.

Why did you close the issue?

**Comment by javiw200s** [comment]
Sorry, I close it unintentionally.

Today morning the problem appears again. The sensor doesn't have the values of next day, it seems that is relted with the data of the sensor.

Thanks.

**Comment by danimart1991** [comment]
I see you don't have the last version of the card. Could you please update?

**Comment by javiw200s** [comment]
The version of the card is v1.2.2. 
Is it the last one?

Thanks.

**Comment by danimart1991** [comment]
Are you sure the version you are using is the 1.2.2? Things like the vertical bar zone is not showed in your screenshots.

Daniel Martín González

________________________________

**Comment by javiw200s** [comment]
When the behaviour is no good the vertical var zone with the current hour and the minimun & maximun indicators (little triangles) disappear.
They appear when the sensor has the data of next day (more of less around 9 PM). But I don't know if is it the cause of one effect.

**Comment by javiw200s** [comment]
Another detail is that with no good behaviour the graphic disappears in dashboards with Tabs. Screenshot 1.
On dashboard without Tabs I haven't seen the graph disappear. Screenshot 2. Var zone and indicators are missing.

This is the behaviour in my Hassio setup.

Thanks.

**Comment by danimart1991** [comment]
Strange behaviour. This is my current dashboard with tabs.

![image](https://user-images.githubusercontent.com/5982912/88928099-aedf4e00-d278-11ea-812b-4d9c15ae5624.png)

Could you include more info like the HA version, the browser, an screenshot with the sensor data, timezone, timezone in HA,...?

**Comment by javiw200s** [comment]
Tested with android mobile, Chrome, Firefox, edge with same behaviour.
Home Assistant 0.113.2 version
![versions](https://user-images.githubusercontent.com/57770725/88931097-abe65c80-d27c-11ea-87cc-0ccfddc66b9e.jpg)
![sensor](https://user-images.githubusercontent.com/57770725/88931109-b0127a00-d27c-11ea-8d49-5cddb4592d08.jpg)

For time zone, please, let me know how to get it.

Thanks

**Comment by danimart1991** [comment]
Ok. I see the error here. Your system has an incorrect TimeZone. Here is the correct data:

![image](https://user-images.githubusercontent.com/5982912/88931780-902f8600-d27d-11ea-917e-3f9137807f20.png)

To set the Timezone in the Host depends on your Host SO. Please google something like "_get and set timezone in [Your distro]_" (Ubuntu in your case I think). 
It seems that you are using Docker, so, for the container "machine" you could set the TimeZome adding the parameter `-e TZ='Europe/Madrid'` in the container configuration.
And finally, to set the TimeZone in HA you could use the `configuration.yaml` file: https://github.com/danimart1991/home-assistant-config/blob/master/configuration.yaml#L7 or set in `Configuration -> General` section.

**Comment by javiw200s** [comment]
Solved.
Adding the below configuration in configuration.yaml file:

homeassistant:
  time_zone: "Europe/Madrid"

Thanks a lot for your help. Now I can enjoy this fantastic card.
