### ISSUE TITLE
Not working in 0.116.0

### ISSUE THREAD

**Issue by McGiverGim** [danimart1991/pvpc-hourly-pricing-card#25]
It seems it has stopped working in Home Assistant 0.116.0. Simply nothing appears. I have not seen any error.

**Comment by gvulvae** [comment]
I confirm the same error.

**Comment by McGiverGim** [comment]
Updated using HACS and now is working. Thanks for the fast fix @danimart1991 !!!

**Comment by fibercool** [comment]
is it working with HA 2020.12.7? first time i installed and i dont know if its a problem of the installation or my HA version.

**Comment by McGiverGim** [comment]
Yes it worked for all the versions until now, at least in my system.

**Comment by fibercool** [comment]
Thanks, i confirm its working fine in HA 2020.12.7, i added with HACS without problem, don't know what i was doing wrong before when i added manually.

**Comment by danimart1991** [comment]
Thanks both for testing.
