### ISSUE TITLE
precio medio periodo

### ISSUE THREAD

**Issue by bocaditos** [danimart1991/pvpc-hourly-pricing-card#27]
Hola. Como sabéis la pvpc con discriminación horaria no te cobra por horas, si no por el precio promedio del periodo valle o pico. Yo tengo una serie de sensores para que me calcule la factura mensual, pero claro, le tengo que poner el precio promedio que yo crea conveniente porque la media de cada periodo cambia todos los días. 
Sería posible que este sensor indicase el precio medio del periodo pico o valle actual para que los sensores de calculo de factura cogieran ese dato del sensor?.
Muchas gracias por el curro.

**Comment by danimart1991** [comment]
Buenas. Gracias por tu aportación.

La tarjeta no crea nuevos sensores. Estos cambios habría que hacerlos en la propia integración.

Por otro lado, un tema bastante recurrente es lo que comentas del promedio. Este cálculo sólo ocurre cuando el contador es analógico. Si el contador es digital SI se cobra por horas consumidas. Por eso cada factura de cada cliente el promedio es distinto, se pone así para resumir. Pero se puede consultar el consumo y precio de esa hora completo.

Daniel Martín González

________________________________

**Comment by bocaditos** [comment]
Hola Daniel, mi nombre es Fernando. Yo estoy en curenergia con contador digital y todos los compañeros cuando les comento esto se quedan perplejos como yo, pero creo que aparte de de curenergia todas las compañias hacen lo mismo, sacan el promedio del pico o valle. Si tienes oportunidad hazlo en esta web que seguramente conozcas, que es una simple calculadora, no sabe lo que consumimos ni a que hora: [https://www.esios.ree.es/es/lumios?rate=rate2&p1=36&p2=58&start_date=27-10-2020T00:00&end_date=21-11-2020T00:00](url)
Saludos

**Comment by danimart1991** [comment]
Hola Fernando.

Quizás el termino de potencia si se calcula con el promedio. Pero no el coste de consumo. Está más que calculado. Si fuera así sería el mismo para todos los que tenemos PVPC. Tanto en la distribuidora, como en la comercializadora puedes ver el consumo por horas y su coste detallado.

![image](https://user-images.githubusercontent.com/5982912/106721983-b0157d00-6605-11eb-8f0e-c77b8940ebf7.png)

![image](https://user-images.githubusercontent.com/5982912/106722026-bd326c00-6605-11eb-8ae6-cdced186ae55.png)

No se suele exponer en las facturas, porque sería una factura bastante extensa. Pero puede calcularse en cualquier momento.

**Comment by bocaditos** [comment]
Curenergia no lo manda así, al menos a mi. Me hace promedio y ya está, por esto la calculadora me cuadra el importe de la factura al céntimo.
Muchas gracias de todas formas, un currazo, lo usamos muchos.
Gracias.

![image](https://user-images.githubusercontent.com/48088472/106733025-ae51b680-6611-11eb-8421-047d43e544e2.png)

**Comment by danimart1991** [comment]
En la web de Curenergia puedes consultar el detalle. En las facturas no se incluye para no hacerlas muy extensas.

**Comment by dbizarro** [comment]
Haz tu mismo la comprobación. Te descargas los consumos de tres periodos. Los sumas y lo divides x los kw. Te sale un "precio medio" que es el que ponen en tu factura. Ese"precio medio" es únicamente tuyo es base a tus consumos y en que precio tenía a esas horas.

Haz lo mismo con alguien de confianza. Verás que ocurre lo mismo. Si puede ser, alguien con perfiles de consumos diferentes a los tuyos.

Solo existe un caso en el que te apliquen un perfil medio de consumo "standard" y únicamente se da cuando el contador inteligente no está en la red de gestión. (No comunica datos a la distribuidora)

**Comment by danimart1991** [comment]
Issue cerrada debido a inactividad y pregunta contestada.
