### ISSUE TITLE
type: custom:pvpc-hourly-pricing-card name: "PVPC 2.0 DHA" entity: sensor.pvpc_2_0_dha

### ISSUE THREAD

**Issue by ortigosano** [danimart1991/pvpc-hourly-pricing-card#28]
Entity not available: sensor.pvpc_2_0_dha

**Comment by danimart1991** [comment]
You need to create the sensor first in **Integrations** section.

**Comment by ortigosano** [comment]
> You need to create the sensor first in **Integrations** section.

Hola y Gracias por responder con tanta celeridad. 

Instalé la Integracion PVPC y funciona sin problemas.
Pero como me gustaría conocer los precios del kw/h "futuros" instalé desde HACKS - Fronted- PVPC Hourly Pricing Card y he reiniciado HA al completo, pero no aparece por nigun sitio la integración llamada sensor.pvpc_2_0_dha solo la sensor.pvpc.

Cuadno agrego una tarjeta vacía en el dashboardo con el siguiente código:

```
type: 'custom:pvpc-hourly-pricing-card'
name: PVPC 2.0 DHA
entity: sensor.pvpc_2_0_dha
```

me muestra ese error:
`Entity not available: sensor.pvpc_2_0_dha`

¿qué estoy haciendo mal?
Gracias

**Comment by danimart1991** [comment]
El nombre de la entidad/sensor tiene que ser el que tu hayas creado. sensor.pvpc_2_0_dha es solo un ejemplo. Si en tu caso es sensor.pvpc tendrás que usar ese.

Daniel Martín González

________________________________

**Comment by danimart1991** [comment]
Hola @ortigosano.

Nada. Encantado de ayudar siempre que pueda.
