### ISSUE TITLE
Nueva factura 2.0TD

### ISSUE THREAD

**Issue by jjprz** [danimart1991/pvpc-hourly-pricing-card#31]
¿Funcionará para la nueva factura 2.0TD?

**Comment by danimart1991** [comment]
Buenas @jjprz 

La card no será actualizada a las nuevas tarifas hasta que como poco estas estén funcionando y @azogue o cualquier otro amable desarrollador actualice la integración en HA. Una vez esté funcional en HA. La card se romperá y habrá que actualizarla con el nuevo código.

**Comment by McGiverGim** [comment]
Parece que el cambio va a ser mínimo, usando la modificación de azogue como custom_component todo sigue funcionando, excepto el icono... entiendo que no distingue en que tramo estamos...

![image](https://user-images.githubusercontent.com/2673520/120276207-adc0e800-c2b2-11eb-8721-43f31579093b.png)

**Comment by McGiverGim** [comment]
Supongo que esto es lo que hay que cambiar:

https://github.com/danimart1991/pvpc-hourly-pricing-card/blob/d8ed9c302751dcc213c35c11d17d803bd824b850/dist/pvpc-hourly-pricing-card.js#L588-L612

La tarifa aparece como `2.0TD`, pero tal vez es mejor esperar a que el cambio sea "oficial" en Home Assistant por si Azogue cambia algo en la integración a última hora...
![image](https://user-images.githubusercontent.com/2673520/120277356-4015bb80-c2b4-11eb-8e27-191f22a62a22.png)

**Comment by jjprz** [comment]
He cambiado esa parte para que coincida con la nueva tarifa. Habrá que estar atentos a los festivos porque no queda muy claro cuales serían. Creo que serían estos más el viernes santo:

["01-01", "01-05", "12-10", "01-11", "06-12", "08-12", "25-12"]

https://github.com/danimart1991/pvpc-hourly-pricing-card/pull/32/commits/164f98705a0467f6a4db57a44b224ab88c4fe59c#

**Comment by azogue** [comment]
@danimart1991 ,

El PR en HA con el quickfix ya está en marcha: https://github.com/home-assistant/core/pull/51320

Espero que, con algo de tiempo, pueda hacer + cambios en la integración en las próximas semanas (hay que tocar el config-flow de la UI, q es lo q + pereza da 😅), y aprovechar para meter + atributos y demás. Me coordinaré contigo!

P.ej, 
- el atributo del **indicador de periodo** (`period: "P1"/"P2"/"P3"`?), 
- de si es fin de semana o festivo nacional (full-valle)
- indicador de periodo de potencia
- precio potencia? (<- ese no lo tengo claro, por unidades, ya que los ~30€/kW año en horas se queda en nada)

¿Se os ocurre alguna más?

**Comment by danimart1991** [comment]
> @danimart1991 ,
> 
> El PR en HA con el quickfix ya está en marcha: [home-assistant/core#51320](https://github.com/home-assistant/core/pull/51320)
> 
> Espero que, con algo de tiempo, pueda hacer + cambios en la integración en las próximas semanas (hay que tocar el config-flow de la UI, q es lo q + pereza da 😅), y aprovechar para meter + atributos y demás. Me coordinaré contigo!
> 
> P.ej,
> 
> * el atributo del **indicador de periodo** (`period: "P1"/"P2"/"P3"`?),
> * de si es fin de semana o festivo nacional (full-valle)
> * indicador de periodo de potencia
> * precio potencia? (<- ese no lo tengo claro, por unidades, ya que los ~30€/kW año en horas se queda en nada)
> 
> ¿Se os ocurre alguna más?

Si. Habrá que ir modificando y adaptando todo poco a poco. 

Me parece bien lo de los periodos, no debería ser difícil sacarlos excepto por los festivos, que igual se puede usar la librería Python que usa HA para la integración de vacaciones/festivos.

Por pedir, añadiría también máximos.

Un saludo y gracias como siempre @azogue

**Comment by danimart1991** [comment]
Closed in #33
