### ISSUE TITLE
Graph not shown since HA 2021.7

### ISSUE THREAD

**Issue by katiuskt** [danimart1991/pvpc-hourly-pricing-card#35]
Hello all

Just updated HA to 2021.7 beta2 version (it includes updated PVPC integration https://github.com/home-assistant/core/pull/51789 ) and the graph shown in this card has stopped to be visible:
![image](https://user-images.githubusercontent.com/75622100/124391967-7bf8d200-dcf3-11eb-8126-adab8a01713e.png)

Other attributes are shown properly. Only the graph seems to be failing after upgrade.

I've just tried with latests stable versions of Firefox and Edge (Chromium based) with no improvement. Browser cache has also been deleted.

I've just noted HA graphs are now slighty different from what they used to be (different colors are used now for instance) so I'm not sure if it could be some change under the hood regarding them it could impact on your card.

Thank you in advance!

**Comment by danimart1991** [comment]
Bug confirmed. It seems that something missing with the new Charts but I can seems want it is.

**Comment by katiuskt** [comment]
In case it helps, I think chart changes done in 2021.7 were done at https://github.com/home-assistant/frontend/pull/9401

**Comment by katiuskt** [comment]
Working like a charm!!
Thank you very much
