### ISSUE TITLE
same color for both curves

### ISSUE THREAD

**Issue by VicenteKER** [danimart1991/pvpc-hourly-pricing-card#37]
I don't know if it's my problem but since version 1.4.0 the two curves appear in the same color (blue) 

![image](https://user-images.githubusercontent.com/79361603/125137246-99bba200-e10c-11eb-8238-004540d209e5.png)

**Comment by danimart1991** [comment]
Hello @VicenteKER 

The graph uses the primary and accent colors of your theme. You could change it in your profile settings.

![image](https://user-images.githubusercontent.com/5982912/125154204-2ee48800-e159-11eb-9e27-59b306f56d4d.png)

**Comment by VicenteKER** [comment]
Gracias Dani.
it worked with 2 colors before the new version 1.4.0 ... And I don't have those options ... 🤔
![image](https://user-images.githubusercontent.com/79361603/125159478-e12b4800-e177-11eb-9add-4e3444f902dc.png)

**Comment by danimart1991** [comment]
I see you are using a Custom Theme. This custom theme defines these two colors, so you need to modify them in the `.yaml` file of the theme or change it in the `.js` file of the card modifying the following lines with the color you want (you could use hexadecimal):

https://github.com/danimart1991/pvpc-hourly-pricing-card/blob/073ec2060311ad34293302da224b14d081fa9cb3/dist/pvpc-hourly-pricing-card.js#L317-L318

For example:
```js
const todayColor = '#123456';
const tomorrowColor = '#654321';
```

**Comment by VicenteKER** [comment]
I will try... thanks. My surprise is that's it worked before with same custom theme...

**Comment by danimart1991** [comment]
I update the card to version 1.4.1 and actually it has the colors fixed.

**Comment by VicenteKER** [comment]
thank you Dani!! 👏👏👏
