### ISSUE TITLE
Graph and peaks show with a 1 hour delay when used in the Canary Islands. 

### ISSUE THREAD

**Issue by airampg** [danimart1991/pvpc-hourly-pricing-card#38]
Dear Daniel, 

First of all, thank you so much for such wonderful card. We all appreciate your efforts. 

However, I have found what seems to be an issue. I am based in the Canary Islands, therefore, my Home Assistant is set up to the Atlantic/Canary time zone, which provides the correct time for me, including Daylight saving in summer. 

It seems like your card may be misinterpreting the information that the PVPC integration feeds it. 

As you can see here, the max price is shown to be at 22h, and the minimum at 4h.
![image](https://user-images.githubusercontent.com/41060873/128888350-b51a4c47-e016-49bd-8a4f-a8163c6798dc.png)

Nonetheless, the data fed by the PVPC integration, which seems correct after cross-checking, differs by 1 hour. 
You can see that the max price is actually shown to be at 21h, and the minimum at 3h.
![image](https://user-images.githubusercontent.com/41060873/128888666-d48ec9b3-35b2-449c-8cff-47afd1bf6d3f.png)

Furthermore, the graph displayed seems to be shifted to the right by 1 hour.
![image](https://user-images.githubusercontent.com/41060873/128889137-b7abb7ba-4fdc-43f5-8474-0a32a73a641e.png)

My gut feeling is that the card is not taking into account the time zone and is somehow adding 1 hour to the data provided by the PVPC integration. That said, I do not know what the issue is and I am not sure it is the card, but this could be a starting point.

Please let me know if there is anything I can help you with.

BR

Airam

**Comment by guaifi** [comment]
Desde la península yo tengo el mismo problema. Antes del cambio de hora tenía 2h de diferencia entre los precios de la web y HA. Ahora después del cambio de hora dejó de funcionar y ya no puedo verlo.

Es bastante molesto ya que con los precios de la luz como están quería programar automatizaciones basadas en el precio.

Gracias!

**Comment by danimart1991** [comment]
Hola @guaifi.

¿La diferencia de horas te sucede en la integración, en la tarjeta o en ambas? ¿has actualizado HA a la última versión?

**Comment by guaifi** [comment]
Hola, la diferencia de horas me sucedía en la integración:

Tomemos como ejemplo el 1 de noviembre: El mínimo real fue a las 4.00 am pero en mi historial aparece a las 5.00

![image](https://user-images.githubusercontent.com/4123625/140490961-45226b7d-f9e3-42e7-aa4f-3d6722106e8f.png)
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/4123625/140491138-b716e1c5-707c-4e9f-b11b-4da87e3d6ddb.png">

Creo que debe haber algún bug en la base probablemente relacionado con horas UTC o algo así.

**Comment by guaifi** [comment]
Perdón por la tontería, tras elaborar el mensaje anterior, y desconfiar de mi configuración de hora UTC resulta que estaba mal.

Para que os funcione correctamente hay que configurar la hora del servidor en Configuración -> Configuración General -> Zona horaria -> Europe/Madrid (para península) ó Atlantic/Canary (para Canarias).

![image](https://user-images.githubusercontent.com/4123625/140493084-8e3148ca-7bb4-4aa6-9b61-9af5e7ef5bd8.png)

Cuando arreglen la integración comprobaré de nuevo si se soluciona el problema.

**Comment by danimart1991** [comment]
Gracias por tus comentarios @guaifi 

Recordad que este repositorio solo hace referencia a la tarjeta, no a la integración.

**Comment by danimart1991** [comment]
Cierro el hilo. Este error debería estar solucionado. De lo contrario, sentíos libres de abrirlo de nuevo o comentar.

I'm going to close the thread. This issue should be fixed. Otherwise, feel free to open it again or comment.
