### ISSUE TITLE
Integration stopped working today 

### ISSUE THREAD

**Issue by hanross2323** [danimart1991/pvpc-hourly-pricing-card#41]
Hi, this integration stopped working today for me. I tried to reload it, to delete and create it again but no luck. 

It seems it’s not retrieving data from url.

**Comment by danimart1991** [comment]
Hi @hanross2323.

This repository is only for the development of the PVPC custom card. The PVPC integration is native from Home Assistant and all the related issues must be in the [Home Assistant repository](https://github.com/home-assistant/core/issues).
