### ISSUE TITLE
Error getting PVPC prices (NaN)

### ISSUE THREAD

**Issue by AdriVillaB** [danimart1991/pvpc-hourly-pricing-card#42]
The card stopped working yesterday or the day before. I'm in the lastest version of HomeAssistant, but it also fails for a friend of mine which is in the previous version, so maybe the problem is that ESIOS changed something on their end.

This is a screenshot of the current content of the card.
![image](https://user-images.githubusercontent.com/1714030/140049746-9dbcaba2-5510-4ff3-b865-41026dab265e.png)

**Comment by danimart1991** [comment]
Hi @AdriVillaB 

This repository is only for the development of the PVPC custom card. The PVPC integration is native from Home Assistant and all the related issues must be in the [Home Assistant repository](https://github.com/home-assistant/core/issues).

Indeed, there is already [an Issue](https://github.com/azogue/aiopvpc/issues/27) in the component used by HA for the integration.

Related Issue: https://github.com/danimart1991/pvpc-hourly-pricing-card/issues/41

**Comment by AdriVillaB** [comment]
Apologies, I though the card takes care of the data parsing process.
