### ISSUE TITLE
PVPC no muestra datos

### ISSUE THREAD

**Issue by archi071** [danimart1991/pvpc-hourly-pricing-card#43]
desde ayer día 2 de Noviembre  a las 20:00 aproximadamente HA no muestra ningún dato.
La integración aparece como no disponible.la tarjeta tampoco muestra ningún dato.
he actualizado e incluso instalado de nuevo pero no funciona. Hoy he comprobado con la instalación de un amigo y tampoco funciona.
Gracias por la integración .

**Comment by danimart1991** [comment]
Hi @archi071.

This repository is only for the development of the PVPC custom card. The PVPC integration is native from Home Assistant and all the related issues must be in the [Home Assistant repository](https://github.com/home-assistant/core/issues).

Indeed, there is already [an Issue](https://github.com/azogue/aiopvpc/issues/27) in the component used by HA for the integration.

Related Issues:
- https://github.com/danimart1991/pvpc-hourly-pricing-card/issues/41
- https://github.com/danimart1991/pvpc-hourly-pricing-card/issues/42
