### ISSUE TITLE
Precios de excedentes de autoconsumo

### ISSUE THREAD

**Issue by sargue** [danimart1991/pvpc-hourly-pricing-card#46]
Propongo una nueva funcionalidad de la tarjeta.

La opción de añadir un nuevo sensor con el precio de venta de excedentes de autoconsumo y que se pinte en la misma gráfica. Propongo utilizar el mismo color del dia (hoy o mañana si disponible) pero utilizando una línea punteada en vez de sólida.

La idea es utilizar el sensor que también proporciona la versión de la integración que funciona con un token: https://github.com/azogue/aiopvpc/pull/35#issuecomment-984023527

**Comment by forast3r** [comment]
Me uno a la propuesta, aplicable también para un uso más general, como por ejemplo comparar gráficamente PVPC con una tarifa con precios fijos en punta, llano o valle.

**Comment by sargue** [comment]
Pues me estoy peleando yo a ver si me sale. De momento he conseguido mostrar en líneas punteadas el tema autoconsumo. Pinta así:

![image](https://user-images.githubusercontent.com/333808/150523433-a7ffd061-5a0f-470c-9163-44a162d65142.png)

Si consigo darle forma ya haré un PR.

**Comment by forast3r** [comment]
> Pues me estoy peleando yo a ver si me sale. De momento he conseguido mostrar en líneas punteadas el tema autoconsumo. Pinta así:
> 
> ![image](https://user-images.githubusercontent.com/333808/150523433-a7ffd061-5a0f-470c-9163-44a162d65142.png)
> 
> Si consigo darle forma ya haré un PR.

Tiene muy buena pinta!

**Comment by sergey08** [comment]
Muy interesante esto

Hay avances?
Esta en Beta?

**Comment by jjvelar** [comment]
> Pues me estoy peleando yo a ver si me sale. De momento he conseguido mostrar en líneas punteadas el tema autoconsumo. Pinta así:
> 
> ![image](https://user-images.githubusercontent.com/333808/150523433-a7ffd061-5a0f-470c-9163-44a162d65142.png)
> 
> Si consigo darle forma ya haré un PR.

Me interesa. Podrías por favor compartir el código?
Gracias!

**Comment by sargue** [comment]
> Me interesa. Podrías por favor compartir el código? Gracias!

El código está compartido desde el inicio.

Código: https://github.com/sargue/pvpc-hourly-pricing-card/blob/pvpc_inyeccion/dist/pvpc-hourly-pricing-card.js
PR asociada con comentarios: https://github.com/danimart1991/pvpc-hourly-pricing-card/pull/47

**Comment by jjvelar** [comment]
Gracias!
