### ISSUE TITLE
Dropdown selector for sensor not working in recent HA versions

### ISSUE THREAD

**Issue by antonio1475** [danimart1991/pvpc-hourly-pricing-card#49]
Instead of a dropdown to select the sensor, a list of sensors is displayed **that doesn't work when clicking it** (it doesn't change the chosen sensor. If the list worked, it would be ok):

![image](https://user-images.githubusercontent.com/63130724/187459151-b4de06fb-f9ca-4d4b-9376-e56438e34c6d.png)

I think a recent HA version broke these dropdowns and some addons/cards need to be updated.

It can be corrected in yaml mode, but impossible in UI mode (plus, the wrong sensor will remain selected, making the graph not work.

Thank you, loving the graph!

**Comment by danimart1991** [comment]
Hello @antonio1475. Thanks for your feedback.

I try to reproduce the bug in two instances of Home Assistant but in all of them the PVPC sensor is automatically selected and I see no list in the editor.

Do you have the latest version of HA and the card? Do you have the PVPC sensor setted? Do you have another cards or add-ons with the same issue? I look for any of them without results.

**Comment by jvcsw** [comment]
I have the same issue. You can select the entity in yaml only.
