### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by McGiverGim** [danimart1991/pvpc-hourly-pricing-card#5]
Hola, estoy viendo este error en el registro. Estoy usando la última versión disponible. La tarjeta funciona así que no tiene pinta de ser muy grave, pero supongo que faltará alguna validación en código o algo.

```txt
Detalles de registro (ERROR)
Logger: frontend.js.latest.202004072
Source: components/system_log/__init__.py:209
First occurred: 13:12:43 (2 occurrences)
Last logged: 13:16:53

http://192.168.100.5:8123/hacsfiles/pvpc-hourly-pricing-card/pvpc-hourly-pricing-card.js:130:31 Uncaught TypeError: Cannot convert undefined or null to object
```

Un saludo y gracias por tu código!!

**Comment by danimart1991** [comment]
Could you give me more info? still happens in the new version (0.0.3)?

**Comment by McGiverGim** [comment]
Yes, it happens with latest version too. Each time I go to the tab with the pvpc card produces this message.
I can see it in the developers tab, registry. But there is no more info on the log.
I will recheck my files to see if I have something wrong...

**Comment by danimart1991** [comment]
What browser and browser version did you use?

**Comment by McGiverGim** [comment]
I have tested it from the Android app, I don't know if it happens too from the computer with a browser. I will try to check it later.

**Comment by McGiverGim** [comment]
It seems that for some reason the card was not updated to version 0.3 and I was using a cached version. A reboot was not enough. I deleted it and added it again and now is working and it seems that the error is gone. Good work!!

I close this issue. If I see the error again I will reopen it.

**Comment by McGiverGim** [comment]
I reopen the issue, it has happened again, but in a different line, according to the error:
```
Logger: frontend.js.latest.202004072
Source: components/system_log/__init__.py:209
First occurred: 25 de abril de 2020 16:55:45 (1 occurrences)
Last logged: 25 de abril de 2020 16:55:45

https://muleronegro.duckdns.org/hacsfiles/pvpc-hourly-pricing-card/pvpc-hourly-pricing-card.js:1:27 Uncaught TypeError: Cannot convert undefined or null to object
```

**Comment by danimart1991** [comment]
I think that you are using an old version of the card or an old version of the card is in the browser cache. Are you using card versioning to fix this issue?

https://www.danielmartingonzalez.com/installing-lovelace-plugins/#versions

**Comment by McGiverGim** [comment]
No, I don't use versioning because I used the HACS installer that adds it automatically.

I will add it manually and monitor it to see if the error happens again. Is probably that you have reason. The error is different that the one from the beginning (point to different line in the code) but I'm not a python developer.

**Comment by McGiverGim** [comment]
I think is better to close (again) this issue. I have not seen the error again. Sorry for making lost your time with this ;)
