### ISSUE TITLE
pvpc hourly pricing card no funciona tras actualización HA

### ISSUE THREAD

**Issue by soysnorre** [danimart1991/pvpc-hourly-pricing-card#50]
Buenos días,

Desde la ultima actualización de HA en Septiembre dicha tarjeta no funciona. Nos encontramos con el siguiente error para tu información @danimart1991 

Custom element doesn't exist: pvpc-hourly-pricing-card.
type: custom:pvpc-hourly-pricing-card
name: PVPC 2.0 DT
entity: sensor.pvpc_2_0_dt

Saludos

**Comment by danimart1991** [comment]
Hola @soysnorre.

La tarjeta funciona correctamente. Por favor revisa que tienes disponible el sensor pvpc_2_0_dt y que te da la información correctamente, así como la instalación de la tarjeta.

Un saludo.

**Comment by vikitor87** [comment]
> Buenos días,
> 
> Desde la ultima actualización de HA en Septiembre dicha tarjeta no funciona. Nos encontramos con el siguiente error para tu información @danimart1991
> 
> Custom element doesn't exist: pvpc-hourly-pricing-card. type: custom:pvpc-hourly-pricing-card name: PVPC 2.0 DT entity: sensor.pvpc_2_0_dt
> 
> Saludos

Hola,

A mi me ha ocurrido lo mismo si instalo directamente la versión1.6.0. Lo que he hecho ha sido instalar la 1.5.1, configurarla e integrarla y después actualizar. De esa forma me ha funcionado correcto. Espero que te sirva.

Saludos.
