### ISSUE TITLE
Card Appearance

### ISSUE THREAD

**Issue by froloffw7** [danimart1991/pvpc-hourly-pricing-card#51]
Hello.
I would like to make some modifications in the card design.
I see how to change the font size, but didn't find how to change the card header location, on my HA screen it is perceptibly lower then on the other other cards, please check screenshot attached.
Can you point me how to change it, as I only see common **ha-card** style, which affect all cards.
![Cards](https://user-images.githubusercontent.com/69122526/203295421-13b6e82a-1b9b-4085-81b7-434e0f2a2192.jpg)

**Comment by danimart1991** [comment]
Hello @froloffw7 

I just updated the card to improve the header style. 😉
