### ISSUE TITLE
Change the height of the graph

### ISSUE THREAD

**Issue by jvcsw** [danimart1991/pvpc-hourly-pricing-card#53]
First of all, thank you for this card.

I propose the option of being able to change the height of the graph (with a fixed minimum and maximum). 

This would allow more flexibility to adapt the card to screens of different sizes and to add in existing panels.

Gracias.

**Comment by feserdel** [comment]
I also support this enhancement. I think it would be useful to have a boolean config parameter, like "zero_baseline", in order to show the graph in more realistic way. For example, today is: 
![PVPC 2023-08-26 092644](https://github.com/danimart1991/pvpc-hourly-pricing-card/assets/118628912/caccaf61-6f4c-4707-938b-147f700fb5b5)

Instead, it could be:

![PVPC ZERO 2023-08-26 094013](https://github.com/danimart1991/pvpc-hourly-pricing-card/assets/118628912/76a97e5d-7d53-4c1b-8f3b-4867bf09e6f4)

**Comment by danimart1991** [comment]
The graph is responsive, so it adapts to the screen size. Sorry but making this behavior "manual" only brings problems with all posible resolutions and devices.

On the other hand, I'm going to publish in few minutes an update with the `baseline_zero` option.

Thanks for your feedback 😉

**Comment by feserdel** [comment]
Now is perfect, thank you very much!!!
![image](https://github.com/danimart1991/pvpc-hourly-pricing-card/assets/118628912/173553b9-0557-41b7-ac1b-4c689274579d)

**Comment by jvcsw** [comment]
Hi, in my case, it isn't perfecte now...

![imagen](https://github.com/danimart1991/pvpc-hourly-pricing-card/assets/37216513/098844b5-384b-45df-9f54-37c2ed10143a)

**Comment by danimart1991** [comment]
> Hi, in my case, it isn't perfecte now... (Type of view: Panel (1 card))
> 
> ![imagen](https://private-user-images.githubusercontent.com/37216513/291197616-098844b5-384b-45df-9f54-37c2ed10143a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4OTI3NjQsIm5iZiI6MTcwMjg5MjQ2NCwicGF0aCI6Ii8zNzIxNjUxMy8yOTExOTc2MTYtMDk4ODQ0YjUtMzg0Yi00NWRmLTlmNTQtMzdjMmVkMTAxNDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA5NDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzM2E1ZDU1MTExNDFkYTQwNTg2ZTc1ODY0ZDFjMzQ3N2M4YmZkYzFjMmE4YTIyNDM4Yzg2NDhlNmI5YmJiOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MZSYhgpobUO4ExAezXBwthN2q3OGlgoyOZZZwJ6unfM)

Fixed in [1.13.0](https://github.com/danimart1991/pvpc-hourly-pricing-card/releases/tag/1.13.0)

![image](https://github.com/danimart1991/pvpc-hourly-pricing-card/assets/5982912/4c0edf2e-af68-455d-a8b5-f6fc46731cd0)

**Comment by jvcsw** [comment]
Yes, thanks.

![imagen](https://github.com/danimart1991/pvpc-hourly-pricing-card/assets/37216513/3915a453-73af-4c6b-a542-2b8173c5b11d)
