### ISSUE TITLE
Graph not shown after upgrading to HA 2023.2

### ISSUE THREAD

**Issue by figorr** [danimart1991/pvpc-hourly-pricing-card#54]
Hi, 

After upgrading HA to version 2023.2 something seems to be broken in the card and the graph is not being shown.

![729CD4E3-0A19-4DFB-9A6E-915AE3FD60DE](https://user-images.githubusercontent.com/77553975/216236048-22b9773f-c3e8-4f14-8b90-92d1dea2e171.jpeg)

![9A53B5BC-589D-421F-864E-1437B4F636C7](https://user-images.githubusercontent.com/77553975/216236084-bfa72a53-336d-4a8a-9ee7-0d95130be91c.png)

![F43DC7AC-B92E-48A1-B8DB-B3FEAE35D597](https://user-images.githubusercontent.com/77553975/216236111-a09d92b5-5e1f-46e5-a693-46735f81eb5c.png)

**Comment by sheaur** [comment]
Igual a mí

**Comment by Agimgrue** [comment]
Same here

**Comment by Cromax81** [comment]
Same :(

**Comment by vtb77** [comment]
The same thing happens to me. Could the change they have made be related to displaying the graphics in real time? Thanks.

**Comment by figorr** [comment]
> The same thing happens to me. Could the change they have made be related to displaying the graphics in real time? Thanks.

Yes, it could be related. They probably changed something at the frontend that affects the graph.

**Comment by Albruaje** [comment]
Igual a mi.

**Comment by Vicente-Ch** [comment]
A mi tambien

**Comment by paloke** [comment]
Misma situación.

**Comment by josemaX** [comment]
Same here, found this in logs:

`Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for esios using this method at custom_components/esios/__init__.py, line 66: hass.config_entries.async_setup_platforms(entry, PLATFORMS)`

**Comment by figorr** [comment]
> Same here, found this in logs:
> 
> `Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for esios using this method at custom_components/esios/__init__.py, line 66: hass.config_entries.async_setup_platforms(entry, PLATFORMS)`

I didn’t remember seeing this after the update or when I restarted HA, but according to the breaking changes of HA 2023.2

[HA 2023.2 breaking changes](https://www.home-assistant.io/blog/2023/02/01/release-20232/)

> Spain electricity hourly pricing (PVPC)
> The previously deprecated YAML configuration of the Spain electricity hourly pricing (PVPC) integration has been removed.
> 
> Spain electricity hourly pricing (PVPC) is now configured via the UI. Any existing YAML configuration has been imported in previous releases and can now be safely removed from your YAML configuration files.
> 
> ([@azogue](https://github.com/azogue) - [#85614](https://github.com/home-assistant/core/pull/85614)) ([documentation](https://www.home-assistant.io/integrations/pvpc_hourly_pricing))

So maybe is detecting you have something at the YAML configuration from a previous setup in YAML.

Did you see that warning message more times (after restarting HA) or just once after updating HA?

**Comment by josemaX** [comment]
> 
> Did you see that warning message more times (after restarting HA) or just once after updating HA?

I've restarted the box (not the core, the machine) and found it on restart

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 17:35:45 (1 occurrences)
Last logged: 17:35:45
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for esios using this method at custom_components/esios/__init__.py, line 66: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

```

```
**uptime**
 17:40:15 up 5 min,  0 users,  load average: 0.05, 0.60, 0.38
```

**Comment by sheaur** [comment]
type: custom:apexcharts-card
update_interval: 5min
header:
  show: true
  title: Precio Electricidad (PVPC)
  show_states: true
  colorize_states: true
  standard_format: true
experimental:
  color_threshold: true
yaxis:
  - id: first
    min: ~0
    max: '|+0.05|'
    show: true
    apex_config:
      tickAmount: 4
      decimalsInFloat: 2
      title:
        text: €/kWh
  - id: second
    opposite: true
    min: 0
    max: '|+2|'
    show: true
    apex_config:
      tickAmount: 4
      decimalsInFloat: 2
      title:
        text: kWh
now:
  show: true
  label: Ahora
graph_span: 1d
span:
  end: day
series:
  - entity: sensor.esios_pvpc
    name: Precio Ahora
    type: line
    color: skyblue
    color_threshold:
      - value: 0.15
        color: green
      - value: 0.2
        color: yellow
      - value: 0.25
        color: orange
      - value: 0.3
        color: orangered
      - value: 0.35
        color: red
    curve: stepline
    yaxis_id: first
    float_precision: 5
    stroke_width: 4
    opacity: 1
    extend_to: now
    show:
      extremas: false
      in_header: true
  - entity: sensor.esios_pvpc
    type: line
    color: green
    color_threshold:
      - value: 0.2
        color: green
      - value: 0.24
        color: yellow
      - value: 0.29
        color: orange
      - value: 0.3
        color: red
    name: Precio Medio
    yaxis_id: first
    float_precision: 5
    stroke_width: 2
    curve: stepline
    opacity: 1
    group_by:
      func: avg
      duration: 24h
    data_generator: |
      let res = [];
      let current_hour = new Date().getHours(); 
      for (const [key, value] of Object.entries(entity.attributes)) {
          if (key.startsWith("price"))
          {
              let hour = key.slice(6,-1);
              let date = new Date(moment({ "hour":hour, "minute":0 }));
              if (date.getHours() >= hour)
              {
                res.push([date.getTime(), value]);
              }
          }      
      }
      return res;
    show:
      extremas: false
      in_header: true
  - entity: sensor.potencia_consumida_hora
    name: Consumo
    type: column
    stroke_width: 5
    yaxis_id: second
    color: red
    float_precision: 3
    group_by:
      func: max
    show:
      extremas: false
      in_header: true
  - entity: sensor.esios_pvpc
    name: Precio
    type: line
    color: brown
    color_threshold:
      - value: 0.15
        color: green
      - value: 0.2
        color: yellow
      - value: 0.25
        color: orange
      - value: 0.3
        color: orangered
      - value: 0.35
        color: red
    curve: stepline
    stroke_width: 4
    opacity: 1
    yaxis_id: first
    float_precision: 5
    extend_to: end
    show:
      extremas: true
      in_header: false
    data_generator: |
      let res = [];
      let current_hour = new Date().getHours(); 
      for (const [key, value] of Object.entries(entity.attributes)) {
          if (key.startsWith("price"))
          {
              let hour = key.slice(6,-1);
              let date = new Date(moment({ "hour":hour, "minute":0 }));
              if (date.getHours() >= hour)
              {
                res.push([date.getTime(), value]);
              }
          }      
      }
      return res;
  - entity: sensor.esios_pvpc
    name: Precio Mañana
    type: line
    color: orange
    color_threshold:
      - value: 0.15
        color: orange
      - value: 0.2
        color: orange
      - value: 0.25
        color: orange
      - value: 0.3
        color: orange
      - value: 0.35
        color: orange
    curve: stepline
    stroke_width: 4
    opacity: 1
    yaxis_id: first
    float_precision: 5
    extend_to: end
    show:
      extremas: true
      in_header: false
    data_generator: |
      let res = [];
      let current_hour = new Date().getHours(); 
      for (const [key, value] of Object.entries(entity.attributes)) {
          if (key.startsWith("price_next_day"))
          {
              let hour = key.slice(15,-1);
              let date = new Date(moment({ "hour":hour, "minute":0 }));
              if (date.getHours() >= hour)
              {
                res.push([date.getTime(), value]);
              }
          }      
      }
      return res;
apex_config:
  chart:
    height: 400px
  legend:
    show: false

**Comment by sheaur** [comment]
He creado esta tarjeta en apexchart, tenéis que cambiar las entidades a vuestra configuración,  mientras no haya solución

**Comment by sheaur** [comment]
![Screenshot_20230203_230005_Home Assistant](https://user-images.githubusercontent.com/66822103/216719169-98c33ad8-da10-4217-a28c-a5a0e39b15c3.jpg)

**Comment by sheaur** [comment]
![Screenshot_20230203_231611_Home Assistant](https://user-images.githubusercontent.com/66822103/216721783-70828523-4a8d-4345-8474-e581af97a48a.jpg)

**Comment by Panchitorr** [comment]
@sheaur Debe haber algún problema con las tabulaciones, porque no consigo que me acepte el código.
![imagen](https://user-images.githubusercontent.com/80638378/216727222-8fab3327-26fd-4db1-bf01-645fec44cfdc.png)

**Comment by sheaur** [comment]
Debes cambiar las -entity por las que tengas configuradas  en mi caso es sensor.esios_pvpc o también el sensor.potencia_consumida_hora que es un sensor que tengo creado para ver el consumo por horas, si no es tu caso quita este último entity

**Comment by Panchitorr** [comment]
Si, eso ya lo he hecho, pero se queda el círculo azul dando vueltas y no me deja darle a "save".

**Comment by sheaur** [comment]
![20230204_002305](https://user-images.githubusercontent.com/66822103/216729140-23211a4b-3fa3-46be-be00-6e88217b9bae.jpg)

**Comment by sheaur** [comment]
Te faltan los guiones "-"

**Comment by Panchitorr** [comment]
Si te fijas, entre "header" y "experimental" está tabulado y faltan más. Al pegarlo aquí se han quitado.
No se si te permitiría adjuntar un .txt aquí con el código. La verdad es que me gusta más tu tarjeta que la otra.

**Comment by antonio1475** [comment]
@sheaur @Panchitorr 
https://docs.github.com/es/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

````
```
Pegad el bloque de código
dentro de 3 tildes así antes y después
```
````

**Comment by sheaur** [comment]
Ok, done

**Comment by sheaur** [comment]
Falta pulir un poco el código pero no me ha dado tiempo a más.

**Comment by Panchitorr** [comment]
Ahora si, muchas gracias @sheaur y @antonio1475

**Comment by Vicente-Ch** [comment]
> ```
> type: custom:apexcharts-card
> update_interval: 5min
> header:
>   show: true
>   title: Precio Electricidad (PVPC)
>   show_states: true
>   colorize_states: true
>   standard_format: true
> experimental:
>   color_threshold: true
> yaxis:
>   - id: first
>     min: ~0
>     max: '|+0.05|'
>     show: true
>     apex_config:
>       tickAmount: 4
>       decimalsInFloat: 2
>       title:
>         text: €/kWh
>   - id: second
>     opposite: true
>     min: 0
>     max: '|+2|'
>     show: true
>     apex_config:
>       tickAmount: 4
>       decimalsInFloat: 2
>       title:
>         text: kWh
> now:
>   show: true
>   label: Ahora
> graph_span: 1d
> span:
>   end: day
> series:
>   - entity: sensor.esios_pvpc
>     name: Precio Ahora
>     type: line
>     color: skyblue
>     color_threshold:
>       - value: 0.15
>         color: green
>       - value: 0.2
>         color: yellow
>       - value: 0.25
>         color: orange
>       - value: 0.3
>         color: orangered
>       - value: 0.35
>         color: red
>     curve: stepline
>     yaxis_id: first
>     float_precision: 5
>     stroke_width: 4
>     opacity: 1
>     extend_to: now
>     show:
>       extremas: false
>       in_header: true
>   - entity: sensor.esios_pvpc
>     type: line
>     color: green
>     color_threshold:
>       - value: 0.2
>         color: green
>       - value: 0.24
>         color: yellow
>       - value: 0.29
>         color: orange
>       - value: 0.3
>         color: red
>     name: Precio Medio
>     yaxis_id: first
>     float_precision: 5
>     stroke_width: 2
>     curve: stepline
>     opacity: 1
>     group_by:
>       func: avg
>       duration: 24h
>     data_generator: |
>       let res = [];
>       let current_hour = new Date().getHours(); 
>       for (const [key, value] of Object.entries(entity.attributes)) {
>           if (key.startsWith("price"))
>           {
>               let hour = key.slice(6,-1);
>               let date = new Date(moment({ "hour":hour, "minute":0 }));
>               if (date.getHours() >= hour)
>               {
>                 res.push([date.getTime(), value]);
>               }
>           }      
>       }
>       return res;
>     show:
>       extremas: false
>       in_header: true
>   - entity: sensor.potencia_consumida_hora
>     name: Consumo
>     type: column
>     stroke_width: 5
>     yaxis_id: second
>     color: red
>     float_precision: 3
>     group_by:
>       func: max
>     show:
>       extremas: false
>       in_header: true
>   - entity: sensor.esios_pvpc
>     name: Precio
>     type: line
>     color: brown
>     color_threshold:
>       - value: 0.15
>         color: green
>       - value: 0.2
>         color: yellow
>       - value: 0.25
>         color: orange
>       - value: 0.3
>         color: orangered
>       - value: 0.35
>         color: red
>     curve: stepline
>     stroke_width: 4
>     opacity: 1
>     yaxis_id: first
>     float_precision: 5
>     extend_to: end
>     show:
>       extremas: true
>       in_header: false
>     group_by:
>       func: max
>       duration: 1m
>     data_generator: |
>       let res = [];
>       let current_hour = new Date().getHours(); 
>       for (const [key, value] of Object.entries(entity.attributes)) {
>           if (key.startsWith("price"))
>           {
>               let hour = key.slice(6,-1);
>               let date = new Date(moment({ "hour":hour, "minute":0 }));
>               if (date.getHours() >= hour)
>               {
>                 res.push([date.getTime(), value]);
>               }
>           }      
>       }
>       return res;
>   - entity: sensor.esios_pvpc
>     name: Precio Mañana
>     type: line
>     color: orange
>     color_threshold:
>       - value: 0.15
>         color: orange
>       - value: 0.2
>         color: orange
>       - value: 0.25
>         color: orange
>       - value: 0.3
>         color: orange
>       - value: 0.35
>         color: orange
>     curve: stepline
>     stroke_width: 4
>     opacity: 1
>     yaxis_id: first
>     float_precision: 5
>     extend_to: end
>     show:
>       extremas: true
>       in_header: false
>     group_by:
>       func: max
>       duration: 1m
>     data_generator: |
>       let res = [];
>       let current_hour = new Date().getHours(); 
>       for (const [key, value] of Object.entries(entity.attributes)) {
>           if (key.startsWith("price_next"))
>           {
>               let hour = key.slice(15,-1);
>               let date = new Date(moment({ "hour": hour, "minute":0 }));
>               if (date.getHours() >= hour)
>               {
>                 res.push([date.getTime(), value]);
>               }
>           }      
>       }
>       return res;
> apex_config:
>   chart:
>     height: 400px
>   legend:
>     show: false
> ```

It worked for me without errors. Try adding this sensor: input_number.export_price_min_asumible

   - entity: input_number.export_price_min_asumible
     name: My Average(-offset)
     type: lines
     stroke_width: 1
     yaxis_id: first
     colour: blue
     float_precision: 5
     group_by:
       func: max
     Show:
       extreme: false
       in_header: true

but it didn't work. This type of entity does not accept it? or is it for another reason. If I make a template saving this entity in a sensor, will it work?
Thank you.

**Comment by Vicente-Ch** [comment]
I make a template, but no run.

###########################################################
### Guarda valor para usarlo en tarjeta apexcharge      ###
###########################################################
  - platform: template
    sensors:
      consigna_precio_pvpc_max:
          friendly_name: 'Precio PVPC MAX asumible'
          unique_id: sensor.precio_pvpv_max_asumible
          value_template: >
                            {{((states.input_number.precio_pvpv_max_asumible.state | float)/100)}}
          unit_of_measurement: '€/kWh'

![image](https://user-images.githubusercontent.com/79970700/216754470-9d17a23d-4596-4458-89a6-a041725d801e.png)

**Comment by danimart1991** [comment]
Buenas noches. Para todos aquellos con problemas con la gráfica de tarjeta PVPC, acabo de subir una nueva versión (1.8.0) que los soluciona. 😎

Agradezco enormemente la paciencia, he tardado varios días en dar con el problema y en poder sacar tiempo, y se agradece el apoyo tanto dando a la estrellita, como a nivel monetario. 🥰

**Comment by Albruaje** [comment]
> Buenas noches. Para todos aquellos con problemas con la gráfica de tarjeta PVPC, acabo de subir una nueva versión (1.8.0) que los soluciona. 😎
> 
> Agradezco enormemente la paciencia, he tardado varios días en dar con el problema y en poder sacar tiempo, y se agradece el apoyo tanto dando a la estrellita, como a nivel monetario. 🥰

Muchas gracias!!!!

**Comment by Vicente-Ch** [comment]
> > Buenas noches. Para todos aquellos con problemas con la gráfica de tarjeta PVPC, acabo de subir una nueva versión (1.8.0) que los soluciona. 😎
> > Agradezco enormemente la paciencia, he tardado varios días en dar con el problema y en poder sacar tiempo, y se agradece el apoyo tanto dando a la estrellita, como a nivel monetario. 🥰
> 
> Muchas gracias!!!!

Si funciona correctamente. Muchas gracias por la rapidez.
Aprobecho para pedirte si sabes alguna forma de tener los prexios de tarifa indexada.
Porque este año ha cambiadoo el PVPC y aunque en este momento apenas hay diferencia entre estas dos tarifas, conforme valla pasando el año van a se rmas diferentes.
Somos muchos q estamos con tarifa indexada, porque la ofrecen varias comercializadoras, Lidera en mi caso.
Como no hay integracion que ofresca este sensor actualmente lo miro con el bot de telegram "Fotovoltaica Bot" te pondria el enlace peeo no logro encontrarlo.
También se puede ver en"precios PVPC" https://t.me/preciospvpc
Bueno, no me lio más y denuevo gracias.
