### ISSUE TITLE
Graph not shown with Home Assistant 2023.2

### ISSUE THREAD

**Issue by davefx** [danimart1991/pvpc-hourly-pricing-card#55]
Since the last HA upgrade to version 2023.2, the graph has disappeared from the card:
![imagen](https://user-images.githubusercontent.com/292309/216923970-a1c655ea-86e9-41bb-8930-db4f0b30e29e.png)

**Comment by danimart1991** [comment]
Hello @davefx 

Yesterday I published an update to fix this issue. Please update the card.

Duplicated issue: #54
