### ISSUE TITLE
I can't uninstall totally the HAC

### ISSUE THREAD

**Issue by vmbajop** [danimart1991/pvpc-hourly-pricing-card#57]
With Home Assistant 2023.2.x, I can't uninstall the hac. Apparently the widget is uninstalled, but in the list of cards it remains. Thanks

**Comment by danimart1991** [comment]
Hello @vmbajop.

Sorry but this issue is not related to this integration. Please, try to restart your Home Assistant instance and clean the cache in your browser. If nothing works, open an issue in the [HACS integrations repository](https://github.com/hacs/integration/issues).

**Comment by vmbajop** [comment]
I'm sorry, I thought that this was interesting for this hack since it is the only one with which it has happened to me, and insistently. BR
