### ISSUE TITLE
Problemas con el cambio horario

### ISSUE THREAD

**Issue by riopedre** [danimart1991/pvpc-hourly-pricing-card#58]
Hoy se ha cambiado la hora y la tarjeta no visualiza bien la gráfica al faltar la información de 02:00 a 03:00. Tampoco indica el valor máximo y mínimo de hoy.
![Screenshot_2023-03-26-16-59-48-707_io homeassistant companion android-edit](https://user-images.githubusercontent.com/20193450/227784809-b782159b-540c-40da-8554-7f9f4608354a.jpg)
Tampoco funciona, tocando la gráfica, que muestre el precio de una hora determinada.

**Comment by figorr** [comment]
Sí, también lo vi. Y además el log se llenaba de errores the frontend después de pasar o tocar la tarjeta.

Pero se arregló justo después de pasar al día siguiente.

Al parecer, a la tarjeta no le sienta bien el cambio horario.  😂

**Comment by feserdel** [comment]
Con el cambio horario de hoy, 31 de marzo, yo también he tenido problemas.

Al parecer falta una hora, las 2 de la mañana.

price_00h: 0.0644
price_01h: 0.06677
price_03h: 0.06724
price_04h: 0.06781

Como consecuencia, no aparecen los precios minimos y maximos de hoy.

También falla la plantilla que uso para calcular el precio medio diario:

```
{% set prices = namespace(values=[]) %}
{% for hour in range(0,23) %}
    {% set prices.values = prices.values + [state_attr('sensor.pvpc', 'price_' ~ '%02d' % hour ~ 'h')] %}
{% endfor %}
{{ (prices.values | sum / prices.values | count) | round(4) }}
```
Dá este error: TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'

Entonces, lo he solucionado así:
```

{% set prices = namespace(values=[]) %}
{% for hour in range(0,23) %}
  {% if state_attr('sensor.pvpc', 'price_' ~ '%02d' % hour ~ 'h') != None %}
      {% set prices.values = prices.values + [state_attr('sensor.pvpc', 'price_' ~ '%02d' % hour ~ 'h')] %}
  {% endif %}
{% endfor %}
{{ (prices.values | sum / prices.values | count) | round(4) }}
```
De momento, parece que funciona.
