### ISSUE TITLE
Icons change

### ISSUE THREAD

**Issue by danimart1991** [danimart1991/pvpc-hourly-pricing-card#6]
I need opinion on the change of icons to something more clarifying for all users. Since it is difficult to find suitable [Material Design icons](https://materialdesignicons.com/). How about using this thumb icons? I accept another approach like animated icons, svg icons,... but must contemplate all three tariff periods (peak, valley and super-valley).

![image](https://user-images.githubusercontent.com/5982912/79630779-92e5ef80-8154-11ea-9ba0-0f15b06fb7df.png)

**Comment by McGiverGim** [comment]
This thumb icons don't say nothing to me... to me is more descriptive the sun and the moon used now.

I have looked at the Material icons but I have not found nothing more suitable :(

**Comment by danimart1991** [comment]
What about something like this but with the new Weather icons?

![image](https://user-images.githubusercontent.com/5982912/80687029-f1528c80-8ac9-11ea-868c-deefae5f869f.png)
merged with
![image](https://user-images.githubusercontent.com/5982912/80686940-d08a3700-8ac9-11ea-839c-e7cfd1c3e098.png)

**Comment by McGiverGim** [comment]
Yes, the idea is good. Is like the current sun and moon but adding the different "dollar" symbols. I looked some days ago for something similar in Material Design Icons but I didn't find any.

If you are capable of draw (or find) this kind of symbols in a "pretty" way it will look good. :)

**Comment by danimart1991** [comment]
I like these icons too and fit into normal tariff too. And when the new rates come into play, the icons will be valid too.

![image](https://user-images.githubusercontent.com/5982912/80698221-73e34800-8ada-11ea-99ae-57ff0e57850c.png)

**Comment by McGiverGim** [comment]
Not too bad neither. I like the idea.

**Comment by jasual2008** [comment]
Buena idea, Dani, ademas también son bastante intuitivos

**Comment by dbizarro** [comment]
> I like these icons too and fit into normal tariff too. And when the new rates come into play, the icons will be valid too.
> 
> ![image](https://user-images.githubusercontent.com/5982912/80698221-73e34800-8ada-11ea-99ae-57ff0e57850c.png)

Estos encajan en lo actual y en lo que nos viene

**Comment by danimart1991** [comment]
### Work done

First Approach: [icons.zip](https://github.com/danimart1991/pvpc-hourly-pricing-card/files/4658389/icons.zip)

![image](https://user-images.githubusercontent.com/5982912/82477135-500a9500-9acf-11ea-97be-13a38bf5997d.png)

### Work left

**Do you have any ideas for the super-valley (electric-car) tariff period?**

**Comment by danimart1991** [comment]
### Super-Valley (Electric-Car) 

Approach (5-minutes photoshop) for the Super-Valley (Electric-Car) icon. What do you think?

![image](https://user-images.githubusercontent.com/5982912/82481434-9236d500-9ad5-11ea-9a85-340cba7deac0.png)

**Comment by McGiverGim** [comment]
Beautiful, but I think is too different from the others two. We pass from a simple line to a line with a complete car. 
Maybe a valley line with something more simple like a car/wheel but using only simple lines?

**Comment by danimart1991** [comment]
A preview: 
![image](https://user-images.githubusercontent.com/5982912/82499200-8f49dd80-9af1-11ea-9b02-9a39a848989d.png)

**Comment by Jaguaza** [comment]
> ### Trabajo hecho
> Primer enfoque: [icons.zip](https://github.com/danimart1991/pvpc-hourly-pricing-card/files/4658389/icons.zip)
> 
> ![imagen](https://user-images.githubusercontent.com/5982912/82477135-500a9500-9acf-11ea-97be-13a38bf5997d.png)
> 
> ### Trabajo restante
> **¿Tiene alguna idea para el período de tarifa del super-valle (automóvil eléctrico)?**

I like these but with a more vivid color please.

**Comment by danimart1991** [comment]
> > ### Trabajo hecho
> > Primer enfoque: [icons.zip](https://github.com/danimart1991/pvpc-hourly-pricing-card/files/4658389/icons.zip)
> > ![imagen](https://user-images.githubusercontent.com/5982912/82477135-500a9500-9acf-11ea-97be-13a38bf5997d.png)
> > ### Trabajo restante
> > **¿Tiene alguna idea para el período de tarifa del super-valle (automóvil eléctrico)?**
> 
> I like these but with a more vivid color please.

The colors are taking from your HA theme. The problem is if your theme has green associated with a blue 😅

**Comment by danimart1991** [comment]
Another approach using icons by felfercab.

$ icons must go in white. And with other colors but...

![image](https://user-images.githubusercontent.com/5982912/82544190-0c5a6e80-9b55-11ea-8741-22f1bc594b96.png)

**Comment by Jaguaza** [comment]
> Another approach using icons by felfercab.
> 
> $ icons must go in white. And with other colors but...
> 
> ![image](https://user-images.githubusercontent.com/5982912/82544190-0c5a6e80-9b55-11ea-8741-22f1bc594b96.png)

No por favor.

**Comment by Jaguaza** [comment]
> > > ### Trabajo hecho
> > > Primer enfoque: [icons.zip](https://github.com/danimart1991/pvpc-hourly-pricing-card/files/4658389/icons.zip)
> > > ![imagen](https://user-images.githubusercontent.com/5982912/82477135-500a9500-9acf-11ea-97be-13a38bf5997d.png)
> > > ### Trabajo restante
> > > **¿Tiene alguna idea para el período de tarifa del super-valle (automóvil eléctrico)?**
> > 
> > 
> > I like these but with a more vivid color please.
> 
> The colors are taking from your HA theme. The problem is if your theme has green associated with a blue 😅

Bien.

**Comment by danimart1991** [comment]
Closed. Thanks for all the help.

Final icons: 

![image](https://user-images.githubusercontent.com/5982912/82586605-1ea9cc00-9b98-11ea-9f8d-bbc3b90b5201.png)

Preview: 
![image](https://user-images.githubusercontent.com/5982912/82586629-2b2e2480-9b98-11ea-9dc4-2308aef424fc.png)
