### ISSUE TITLE
Desde ayer 12.05.2023, no se muestran datos en la integración de PVPC en Home Assistant

### ISSUE THREAD

**Issue by jumate** [danimart1991/pvpc-hourly-pricing-card#60]
Este error se originó a partir de una integración personalizada.

Logger: homeassistant.config_entries
Source: custom_components/pvpc_hourly_pricing/__init__.py:102
Integration: Spain electricity hourly pricing (PVPC)
First occurred: 10:48:16 (1 occurrences)
Last logged: 10:48:16

Error setting up entry PVPC for pvpc_hourly_pricing
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/pvpc_hourly_pricing/__init__.py", line 102, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by danimart1991** [comment]
Hola.

La tarjeta no usa la API de Esios. Usa los datos que da la integración PVPC de Home Assistant que si que usa la API de Esios. Tendrás que abrir una Issue en el repositorio de Home Assistant Core, o en su defecto, en la librería que usa la integración del gran @azogue.

Un saludo y gracias.
