### ISSUE TITLE
Añadir un atributo con el precio medio diario

### ISSUE THREAD

**Issue by feserdel** [danimart1991/pvpc-hourly-pricing-card#64]
Buenos días, creo que sería útil disponer de un atributo con el precio medio diario para cada día.

Este valor se puede usar en automatizaciones, por ejemplo:

- Activar determinados aparatos (lavadoras, lavavajillas, bombas de calor, etc.) cuando el precio actual sea inferior al precio medio diario, pero no cuando sea superior.
- Carga de baterías desde la red, cuando la batería está descargada por debajo de un determinado nivel, en horario nocturno, siempre que el precio en ese horario sea inferior al precio medio diario. Esto suele suceder en los días de diario L-V pero no en fines de semana.

De hecho estoy desarrollando una automatización para este fin, pero tendría que calcular el precio medio, y sería más fácil si la integración me lo entrega.

**Comment by danimart1991** [comment]
Hola @feserdel. Gracias por tu comentario.

Este repositorio solo incluye la tarjeta que muestra la información que proviene de la integración PVPC disponible de manera nativa en Home Assistant. El desarrollo de esta integración y la petición que realizas deberías hacerla en el repositorio de [Home Assistant Core](https://github.com/home-assistant/core/issues).

En cualquier caso, como idea, Home Assistant dispone ahora de varios ayudantes que pueden crear un sensor con la información que solicitas. Puedes realizar un ayudante de tipo sensor template que sume el valor de todos los atributos de precio y calcule el precio medio de todos ellos.

**Comment by feserdel** [comment]
Muchas gracias. Por lo que he visto, los "helpers" de estadísticas se aplican a los valores de un sensor, pero no a sus atributos. Lo que había pensado es desarrollar un script en python que lo calcule (usando [hacs-pyscript](https://hacs-pyscript.readthedocs.io/en/latest/)). Bueno, ya veré que hago. Gracias de todos modos.

**Comment by danimart1991** [comment]
¿Por qué complicarse tanto para hacer algo tan sencillo? 

- Puedes hacer en `configuration.yaml` un [`sensor template`](https://www.home-assistant.io/integrations/template#state-based-template-binary-sensors-buttons-images-numbers-selects-and-sensors) que haga el cálculo.
- Puedes hacer lo mismo de manera visual usando un ayudante de tipo `Template -> Sensor`.

```jinja2
{% set prices = namespace(values=[]) %}
{% for hour in range(0,23) %}
    {% set prices.values = prices.values + [state_attr('sensor.pvpc', 'price_' ~ '%02d' % hour ~ 'h')] %}
{% endfor %}
{{ prices.values | sum / prices.values | count }}
```

![image](https://github.com/danimart1991/pvpc-hourly-pricing-card/assets/5982912/82b9bf3c-279f-4a7f-9ff4-fa4338ce5cad)

**Comment by danimart1991** [comment]
¿Por qué complicarse tanto para hacer algo tan sencillo? 

- Puedes hacer en `configuration.yaml` un [`sensor template`](https://www.home-assistant.io/integrations/template#state-based-template-binary-sensors-buttons-images-numbers-selects-and-sensors) que haga el cálculo.
- Puedes hacer lo mismo de manera visual usando un ayudante de tipo `Template -> Sensor`.

```jinja2
{% set prices = namespace(values=[]) %}
{% for hour in range(0,23) %}
    {% set prices.values = prices.values + [state_attr('sensor.pvpc', 'price_' ~ '%02d' % hour ~ 'h')] %}
{% endfor %}
{{ prices.values | sum / prices.values | count }}
```

![image](https://github.com/danimart1991/pvpc-hourly-pricing-card/assets/5982912/82b9bf3c-279f-4a7f-9ff4-fa4338ce5cad)

**Comment by feserdel** [comment]
Efectivamente, funciona!!. Muchas gracias. 
La verdad es que no soy muy ducho en plantillas de HA, pero ya veo que tu sí.
Finalmente quedó así:

![image](https://github.com/danimart1991/pvpc-hourly-pricing-card/assets/118628912/ff28152a-4c69-40f6-9534-d934b194ddff)

Con el código:

```
{% set prices = namespace(values=[]) %}
{% for hour in range(0,23) %}
    {% set prices.values = prices.values + [state_attr('sensor.pvpc', 'price_' ~ '%02d' % hour ~ 'h')] %}
{% endfor %}
{{ (prices.values | sum / prices.values | count) | round(4) }}

```
Gracias una vez más.
