### ISSUE TITLE
No muestra grafico en Ipad

### ISSUE THREAD

**Issue by Osconse** [danimart1991/pvpc-hourly-pricing-card#65]
![20231215_182125](https://github.com/danimart1991/pvpc-hourly-pricing-card/assets/98707422/231f8204-9773-4d33-8ef8-dc874f3ed296)
Hola, tengo la tarjeta actualizada y funcionando correctamente. Funciona con normalidad en mi pc con windows 11 y en varios telefonos android, pero en un viejo iPad con iOS 12.5.7 que usamos de wallpanel ya no lo muestra y nos saca el error de la foto (perdén por la mala calidad).

Anteriormente ha funcionado pero ya no. Ayer me saltó una actualización de la card y ahora tengo la versión 1.12.0
Sabéis que puede pasar?

Gracias

**Comment by danimart1991** [comment]
Hola @Osconse. 

¿Tienes HA actualizado a la última versión? He cambiado los componentes del editor para que se adapten a las últimas versiones del frontend de Home Assistant. No debería afectar, pero si tienes problemas con otros componentes de HA, es posible que también los tengas con este.

En cualquier caso, también puede ser cache, prueba a borrar el cache de la aplicación y así que recargue la tarjeta.

**Comment by Osconse** [comment]
Hola, gracias por responder.Tengo Home Assistant en la última versión 2023.12.3 y todo lo demás totalmente actualizado.No tengo ningún problema con ningún otro componente. Tan solo esa tarjeta y tan solo en el iPad.El problema lo tengo en un viejo iPad pero ahí está corriendo Home Assistant a través de app y no del navegador. Quizás sea eso?Gracias Enviado desde mi Galaxy
-------- Mensaje original --------De: Daniel Martin Gonzalez ***@***.***> Fecha: 16/12/23  9:11  (GMT+01:00) Para: danimart1991/pvpc-hourly-pricing-card ***@***.***> Cc: Osconse ***@***.***>, Mention ***@***.***> Asunto: Re: [danimart1991/pvpc-hourly-pricing-card] No muestra grafico en Ipad (Issue #65) 
Hola @Osconse.
¿Tienes HA actualizado a la última versión? He cambiado los componentes del editor para que se adapten a las últimas versiones del frontend de Home Assistant. No debería afectar, pero si tienes problemas con otros componentes de HA, es posible que también los tengas con este.
En cualquier caso, también puede ser cache, prueba a borrar el cache de la aplicación y así que recargue la tarjeta.
