### ISSUE TITLE
Feature request: Add current hour to the graph

### ISSUE THREAD

**Issue by McGiverGim** [danimart1991/pvpc-hourly-pricing-card#7]
I think it will be interesting to add some kind of symbol to the graph, in this way we can see directly at which point we are, without looking at the hour. Maybe a simple vertical line in the current hour, or a change in the background color dividing the past and the future will be enough. 
Or maybe the result is very bad, I can't say. :)

**Comment by danimart1991** [comment]
Good idea. I add it to the roadmap.

**Comment by danimart1991** [comment]
@McGiverGim what do you think about this implementation? I think the areas dividing the past and the future generates confusion when the "next day" data is showed.

![image](https://user-images.githubusercontent.com/5982912/80376403-0b0d8d00-889a-11ea-948d-2d7e73789909.png)

**Comment by McGiverGim** [comment]
It's perfect! It shows the current hour, more than enough!

**Comment by danimart1991** [comment]
Feature available in v0.0.4

**Comment by McGiverGim** [comment]
One thing more: you can't mark the hour 23:00 to 00:00 because the last segment is missing 😉

**Comment by danimart1991** [comment]
> One thing more: you can't mark the hour 23:00 to 00:00 because the last segment is missing 😉

@McGiverGim fixed. 😉

**Comment by McGiverGim** [comment]
Tested and working!!
